---
include:
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
